$font = Noto Sans

general {
   hide_cursor = false
}

animations {
   enabled = true
   bezier = smooth, 0.25, 0.1, 0.25, 1.0
   animation = fadeIn, 1, 5, smooth
   animation = fadeOut, 1, 5, smooth
   animation = inputFieldDots, 1, 2, smooth
}

background {
   monitor =
   path = /home/shimigui/Pictures/lock
   blur_passes = 1
}

label {
   monitor =
   text = $TIME
   color = rgba($HHEX_FGff)
   font_size = 110
   font_family = $font
   position = 0, 140
   halign = center
   valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%d/%m/%Y"
    color = rgba($HHEX_FGff)
    font_size = 20
    font_family = $font
    position = 0, 40
    halign = center
    valign = center
}

input-field {
   monitor =
   rounding = 2
   size = 20%, 4%
   outline_thickness = 2
   font_color = $HHEX_PRIMARY_OPAQUE
   inner_color = rgba($HHEX_BG0f)

   outer_color = $HHEX_PRIMARY_OPAQUE
   check_color = rgba(a6e3a1ff)
   fail_color = rgba(f38ba8ff)

   position = 0, -80
   halign = center
   valign = center

   fail_text = $PAMFAIL$FPRINTFAIL
   check_text = Authenticating...
}
